language: python

python:
  - 3.6

addons:
  - postgresql: "9.5"

before_install:
  - export DJ_DEBUG=False
  - export DABABASE_URL=postgres://postgres@localhost/travisdb

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  # - python captaincook/manage.py migrate --noinput

env:
  - DJANGO=1.9.10

script:
  - make collectstatic
  - make tests

deploy:
  run:
     - |
        cat >~/.netrc <<EOF
        machine api.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_TOKEN
        machine git.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_TOKEN
        EOF
      - chmod 600 ~/.netrc # Heroku cli complains about permissions without this
      - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - git push git@heroku.com:staging-mixs-app.git $CIRCLE_SHA1:refs/heads/master